"""Update Game model to use Integer field for phone number

Revision ID: 6cf82bfb71fd
Revises: 34c97af5d199
Create Date: 2024-02-27 07:26:24.305830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf82bfb71fd'
down_revision = '34c97af5d199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('host_phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('host_phone',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
