"""Description of migration

Revision ID: 745a2d3dd6e3
Revises: 8d25fcb8abff
Create Date: 2024-02-13 22:48:58.792531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745a2d3dd6e3'
down_revision = '8d25fcb8abff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turf_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turf_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['turf_id'], ['turf.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turf_review')
    # ### end Alembic commands ###
